7-урок: Работа с асинхронным кодом. Fetch API
js-tasks-ru/js-20201211_a-a-aituganov pull request #10
Opened 2021-01-11 13:55 UTC by conttroll

@dosandk в задаче ColumnChart запрашивает данные, рисует колонки, обновляет, в нетворке все показывает, но некоторые пункты теста не проходит, не могу понять

2021-01-11 14:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ColumnChart компонент с динамической загрузкой данных
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have property 'chartHeight'
+ should have loading indication if data wasn't passed 
+ should have ability to be destroyed
- should render data correctly
- should have ability to be update by new values
```

2021-01-11 22:53 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const promise = new Promise((resolve) => {
эта конструкция здесь лишняя - ее нужно убрать. Процесс создания `url` не должен быть асинхронный

2021-01-11 22:55 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const promise = new Promise((resolve) => {
также, данную конструкцию нужно убрать. Достаточно просто:
```
const newUrl = new URL(`https://course-js.javascript.ru/${this.url}`);
newUrl.searchParams.set('from', from.toISOString());
newUrl.searchParams.set('to', to.toISOString());

fetchJson(newUrl)
```

2021-01-11 22:55 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-01-13 04:54 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2021-01-13 04:59 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2021-01-13 05:05 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable v3 с динамической загрузкой данных и "infinity scroll"
+ should be rendered correctly
+ should call "loadData" method
+ should render loaded data correctly
+ should sort data correctly
+ should have ability to be destroyed
```
```diff
ColumnChart компонент с динамической загрузкой данных
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have property 'chartHeight'
+ should render data correctly
+ should have ability to be update by new values
+ should have loading indication if data wasn't passed 
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-13 05:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-13 23:18 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +      const response = await fetchJson(newUrl);
good 👍

2021-01-13 23:18 UTC, dosandk approved these changes
good 👍

2021-01-13 23:19 UTC, merged