2nd task
js-tasks-ru/js-20201211_a-a-aituganov pull request #2
Opened 2020-12-16 05:39 UTC by conttroll

в этом PR решены задачи: 1-intro & 02-javascript-data-types.

2020-12-16 05:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
Первая задача
+ should return sum of numbers
```

2020-12-16 06:38 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-17 23:30 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return newArr.sort((a, b) => a.localeCompare(b, 'ru-en', {caseFirst: "upper"}));
строка 12 дублирует строку 15, за исключением порядка аргументов в методе `localeCompare` - необходимо избавиться от этого дублирования

2020-12-17 23:30 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let filtered = Object.entries(obj).filter(el => fields.includes(el[0]));
может `const`?

2020-12-17 23:31 UTC, dosandk requested changes
необходимо внести изменения согласно комментариям

2020-12-18 06:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 15:06 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    } else if (param === 'desc') return newArr.reverse();
хорошо, от дубликатов мы избавились. 
Но возможно мы сможем избавиться от `reverse` и сортировать массив сразу в нужно порядке?

2020-12-18 15:06 UTC, dosandk requested changes
необходимо внести правки в решение `sortStrings`

2020-12-18 17:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-19 07:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-20 13:25 UTC, dosandk approved these changes

2020-12-20 13:26 UTC, merged